### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by TheMikeyR** [bochinski/iou-tracker#1]
**Question 1:** How this the algorithm behave in a scenario with two tracks of two persons, where the detector fails to detect one person in one frame but manage to detect the person in the next frame. Will it recover the track or simple assign it a new trackid?

**Question 2:** Any plans to make an online version of this algorithm (like SORT) ?

**Comment by bochinski** [comment]
**Answer  1:** If there is a "missing detection" the track will be terminated. If one or more frames later a detection is received which could belong to the first track, a new track with a new ID is started. Currently there is no option to recover a track. Obviously this can cause a lot of ID switches that seem unnecessary but can also prevent some other failure cases. Anyway, here is of course a lot of room for improvement, but for the sake of simplicity (to prove the point in the paper) no strategy for track recovery was included in the current work.

**Answer 2:** If the time allows, i may implement and evaluate an online version of the tracker. The most straightforward approach would be to remove the filtering for sigma_h and t_min, but then the performance will degrade (probably a lot).

**Comment by TheMikeyR** [comment]
Thanks for your answer! @bochinski
