### ISSUE TITLE
CVPR19 MOT Data

### ISSUE THREAD

**Issue by nicolaerosia** [bochinski/iou-tracker#11]
Hello,

First of all, thank you for posting the V-IOU code :)
I would like to reproduce the results that you've obtained on CVPR19 MOT Data but I can't seem to find where to download it from.

The links https://motchallenge.net/data/CVPR_2019_Tracking_Challenge/ and https://motchallenge.net/data/CVPR_2019_Detection_Challenge/ are not working.

Do you happen to have the data? If yes, could you please drop me a link to download it?

Thanks a lot,
Nicolae

**Comment by bochinski** [comment]
Hi,
It would be better if you ask the people behind the motchallenge / authors of https://arxiv.org/abs/1906.04567 to make the data available again.

If you get no answer you can send me an email and I may share the files with you but I am not feeling comfortable in hosting the dataset publicly.

**Comment by bochinski** [comment]
The data seems to be available again at https://motchallenge.net/data/CVPR_2019_Tracking_Challenge/
